server:
  port: 8085

spring:
  application:
    name: RAILWAY-API-GATEWAY
  data:
    mongodb:
      uri: mongodb+srv://vManav123:root@cluster1.dxvl7.mongodb.net/User-Management-System?retryWrites=true&w=majority
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: RAILWAY-RESERVATION-SERVICE
          uri: lb://RAILWAY-RESERVATION-SERVICE
          predicates:
            - Path=/trains/**
        - id: USER-MANAGEMENT-SERVICE
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/user/**
        - id: RAILWAY-APPLICATION-SYSTEM
          uri: lb://RAILWAY-APPLICATION-SYSTEM
          predicates:
            - Path=/application/**
        - id: BANK-MANAGEMENT-SERVICE
          uri: lb://BANK-MANAGEMENT-SERVICE
          predicates:
            - Path=/bank/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    ip-address: 127 .0.0.1
swagger:
  config:
    refreshrate: 5000
